version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
os: Visual Studio 2017
configuration: Release
platform:
- x64
skip_tags: true
before_build:
- cmd: git rev-parse --short HEAD>commit.txt && set /p GIT_COMMIT_SHORT=<commit.txt
- cmd: pushd . && cd FluentTerminal.Client && npm install && npm run-script build && popd && nuget restore FluentTerminal.sln
after_build:
- cmd: '7z a FluentTerminal-v%APPVEYOR_BUILD_VERSION%-%GIT_COMMIT_SHORT%.zip FluentTerminal.App\AppPackages\*'
artifacts:
  - path: 'FluentTerminal-v%APPVEYOR_BUILD_VERSION%-${GIT_COMMIT_SHORT}.zip'
    name: AppPackage
build_script:
  - msbuild /maxcpucount:%NUMBER_OF_PROCESSORS% /t:Build /p:Configuration=Release /p:AppxBundle=Always /p:Platform="x64" /v:q /nologo FluentTerminal.sln
test_script:
  - echo Skipt tests run
deploy:
  release: 'FluentTerminal-%APPVEYOR_BUILD_VERSION%-${GIT_COMMIT_SHORT}'
  description: 'Build ${APPVEYOR_REPO_COMMIT} on master branch'
  provider: GitHub
  auth_token:
    secure: bpe1pOH5cgXfb5MrVDh9yUiwDeydqWlk9GOR8VB598VKQgiWU3lcwS8CJOT172YU
  draft: false
  prerelease: false
  on:
    branch: master
